# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6224f7e4cbd3902b187195571c7e8ce9131f935b3c96ccefca487d05f197bf407902cf9af9a8e9c643fa0deabdbfe55abd6539c782fe8dc522f8db21f3051f4b

test:
  secret_key_base: f47477da6877c5e1f5023cdfdc03d966142bbe444f916800f240c02d1da5f09007f17ff3d761328701c339c6e08cb9337c3cb326ae72990001e5dc18102c9bc9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
